name: card_customization
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.8.1







dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  flutter_colorpicker: ^1.0.3
  equatable: ^2.0.5
  http: ^1.2.1
  flutter_image_compress: ^2.2.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  mocktail: ^1.0.3





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/
